---
- name: create the realm
  command: "{{ container_exec_cmd }} radosgw-admin realm create --rgw-realm={{ rgw_realm }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: "'No such file or directory' in realmcheck.stderr"

- name: create the zonegroup
  command: "{{ container_exec_cmd }} radosgw-admin zonegroup create --rgw-realm={{ rgw_realm }} --rgw-zonegroup={{ rgw_zonegroup }} --endpoints={{ rgw_multisite_proto }}://{{ rgw_multisite_endpoint_addr }}:{{ radosgw_frontend_port }} --master"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: "'No such file or directory' in zonegroupcheck.stderr"

- name: create the zone
  command: "{{ container_exec_cmd }} radosgw-admin zone create --rgw-realm={{ rgw_realm }} --rgw-zonegroup={{ rgw_zonegroup }} --rgw-zone={{ rgw_zone }} --endpoints={{ rgw_multisite_proto }}://{{ rgw_multisite_endpoint_addr }}:{{ radosgw_frontend_port }} --access-key={{ system_access_key }} --secret={{ system_secret_key }} --master"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: "'No such file or directory' in zonecheck.stderr"

- name: create the zone user
  command: "{{ container_exec_cmd }} radosgw-admin user create --rgw-realm={{ rgw_realm }} --rgw-zonegroup={{ rgw_zonegroup }} --uid={{ rgw_zone_user }} --display-name=\"Zone User\" --access-key={{ system_access_key }} --secret={{ system_secret_key }} --system"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: "'could not fetch user info: no user info saved' in usercheck.stderr"
  notify: update period

- name: add other endpoints to the zone
  command: "{{ container_exec_cmd }} radosgw-admin zone modify --rgw-realm={{ rgw_realm }} --rgw-zonegroup={{ rgw_zonegroup }} --rgw-zone={{ rgw_zone }} --endpoints {{ rgw_multisite_endpoints_list }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: rgw_multisite_endpoints_list is defined
  notify: update period
