- name: convert period_pull to json
  set_fact:
    period_pull_json: "{{ period_pull.stdout | from_json }}"

- name: get zonegroups list from json_output
    set_fact:
      zonegroups: "{{ period_pull_json['period_map']['zonegroups'] }}"

- name: get zones from zonegroups list
  set_fact:
    zonegroups_endpoints: "{{ zonegroups_endpoints | default([]) }} + {{ item.value.endpoints }}"
  with_dict: "{{ zonegroups }}"

- name: get zones from zonegroups list
  set_fact:
    zones: "{{ zones | default([]) }} + {{ item.zones }}"
  with_items: "{{ zonegroups }}"
  when: item.name == "{{ rgw_zonegroup }}"

- name: get endpoints from zones list
  set_fact:
    zone_endpoints: "{{ zone_endpoints | default([]) }} + {{ item.endpoints }}"
  with_items: "{{ zones }}"
  when: item.name != "{{ rgw_zone }}"

- name: ensure connection to zonegroups endpoints
  uri:
    url: "{{ item }}"
  with_items: "{{ zonegroups_endpoints }}"

- name: ensure connection to zones endpoints
  uri:
    url: "{{ item }}"
  with_items: "{{ zone_endpoints }}"
